/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Filtering_IppFilteringTest */

#ifndef _Included_Filtering_IppFilteringTest
#define _Included_Filtering_IppFilteringTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Filtering_IppFilteringTest
 * Method:    filtering
 * Signature: (I[FIDDD)[F
 */
JNIEXPORT jfloatArray JNICALL Java_Filtering_IppFilteringTest_filtering
  (JNIEnv *, jclass, jint, jfloatArray, jint, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
