/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Filtering_IppFiltering */

#ifndef _Included_Filtering_IppFiltering
#define _Included_Filtering_IppFiltering
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Filtering_IppFiltering
 * Method:    filtering
 * Signature: (I[FIDDD)I
 */
JNIEXPORT jint JNICALL Java_Filtering_IppFiltering_filtering
  (JNIEnv *, jclass, jint, jfloatArray, jint, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
