/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RecordAndProcessing_filtering_IppFiltering */

#ifndef _Included_RecordAndProcessing_filtering_IppFiltering
#define _Included_RecordAndProcessing_filtering_IppFiltering
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RecordAndProcessing_filtering_IppFiltering
 * Method:    filtering
 * Signature: (I[FIDDD)I
 */
JNIEXPORT jint JNICALL Java_RecordAndProcessing_filtering_IppFiltering_filtering
  (JNIEnv *, jclass, jint, jfloatArray, jint, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
